name: anime
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 700
